### ISSUE TITLE
issue with Travis

### ISSUE THREAD

**Issue by DivadNojnarg** [rstudio/fontawesome#2]
Dear Rich, 

Thanks for this package which solves a lot of non displaying icons issues in https://github.com/DivadNojnarg/bs4Dash.

However, since I included it in the imports of my package, I end up with a Travis building error:
```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
missing: fontawesome

```

Regards

David

**Comment by rich-iannone** [comment]
Thanks for reporting this. We'll get this package onto Travis ourselves very soon and sort out this build error.

**Comment by wch** [comment]
@DivadNojnarg The issue is that fontawesome is listed as an Import for your package, but fontawesome is not yet on CRAN. You probably need to add `Remotes: rstudio/fontawesome` to your DESCRIPTION file.

For example, see https://github.com/rstudio/shiny/blob/026b7278c16612aa4277a3298d6a6e8e758482d3/DESCRIPTION#L92-L94

**Comment by rich-iannone** [comment]
Thanks @wch !

**Comment by DivadNojnarg** [comment]
Fixed on Travis. Thanks @wch and @rich-iannone
