### ISSUE TITLE
Combine efforts with icon package?

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/fontawesome#6]
The [icon](https://github.com/ropenscilabs/icon) package was created in October 2017 with identical usecase to this one. It even uses the same base function name: `fa()`. At the moment its scope is maybe slightly broader than this package with some additional icon sets.

Since `icon` is still under active maintenance, it might be worth seeing if the authors would accept PRs for anything you think is missing. At the very least it'd be polite to acknowledge the prior art in the README, even though it is probable you happened upon the same function name by coincidence.

**Comment by rich-iannone** [comment]
Definitely yes! to all the possible actions you've outlined. We found out about (rediscovered?) the work done in **icon** a few days after we were well underway with this package. Once it was learned that this would essentially reproduce much of icon we decided that we would do our best to contribute wherever possible to **icon** (e.g., help fix issues, contribute useful new ideas).

We are actually trying to pull out and centralize those shared dependencies between **rmarkdown**, **shiny**, et al. This is to ease the burden of updating JS libs and CSS stylesheets in the `htmltools::htmlDependency()`s multiple times, across those packages. The **fontawesome** package and the (currently private) **htmldeps** package are part of this effort.

Anyway, the first thing I'll do is provide acknowledgements of similar packages and functions in the README. Once, we get a better handle on the direction of **fontawesome**, we will work toward helpful PRs for **icon**!

**Comment by MilesMcBain** [comment]
That's great to hear! :clap:

**Comment by wch** [comment]
Just a bit more context about why we created this package: It will be used by some packages from RStudio, so there are some restrictions and responsibilities that we're faced with that we can't impose on a package maintained by someone else. For example, we need to be extra careful when making updates to not break backward compatibility, because any users of Shiny and rmarkdown could potentially be affected. It also means that if any high priority issues come up, we need to fix them right away and release an update. It also allows us to create an API that may be different from the existing icon package, without breaking code for users of that package.

**Comment by rich-iannone** [comment]
Sorry for the long delay in responding to this. I think that you raise some great points, however, we don't even really have a good handle on the direction of this package yet (do we use web fonts? is it SVG all the way? etc.) There are many approaches we could take and, at this point, we need some time to figure this out.

I guess what I'm saying is that we're really not in a good place right now with this package to invite collaboration. I think this will change soon but we do need some time to do some experimentation and then get a solid plan in place.
