### ISSUE TITLE
Examples missing from the pkgdown website homepage

### ISSUE THREAD

**Issue by IndrajeetPatil** [rstudio/fontawesome#91]
I am not sure why, but the very useful _Examples_ section, which is [present](https://github.com/rstudio/fontawesome/blob/main/README.md#examples) in `README.md` is missing from the pkgdown website homepage:

<img width="1187" alt="Screenshot 2022-07-02 at 14 27 54" src="https://user-images.githubusercontent.com/11330453/177000850-1b2d4ca4-1eed-4199-b773-2ccf1edfed64.png">

**Comment by rich-iannone** [comment]
I did this on purpose (with https://github.com/rstudio/fontawesome/blob/main/index.md) to keep the project page a bit shorter and more to the point. This set of examples is better served in a Getting Started article (which I actually don't have right now :( ). Thanks for raising this issue, but I'm going to close this Issue since this was all intentional.
